# Generated by Django 6.0.5 on 2026-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_background_id_passwordresetotp'),
    ]

    operations = [
    ]
