# Generated by Django 6.0.5 on 2026-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_setup_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
