# Generated by Django 5.2.7 on 2026-07-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_category_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
