# Generated by Django 5.2.7 on 2026-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_livestream_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestream',
            old_name='stream_url',
            new_name='youtube_live',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='video_url',
        ),
        migrations.AddField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('UPCOMING', 'UPCOMING'), ('ENDED', 'ENDED')], default='UPCOMING', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='duration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='instructor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/videos/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='thumbnail',
            field=models.ImageField(upload_to='livestreams/'),
        ),
    ]
