# Generated by Django 5.2.7 on 2026-07-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_stream_url_livestream_youtube_live_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='livestreams/'),
        ),
    ]
