# Generated by Django 5.2.7 on 2026-07-04 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_livestream_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('UPCOMING', 'Upcoming'), ('ENDED', 'Ended')], default='UPCOMING', max_length=20),
        ),
    ]
