# Generated by Django 5.2.7 on 2026-07-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_photo_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='default.jpg', max_length=150),
        ),
    ]
