# Generated by Django 5.2.7 on 2026-07-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_chatmessage_edited_remove_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
