# Generated by Django 5.2.7 on 2026-07-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_chatmessage_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat/voice/'),
        ),
    ]
