# Generated by Django 5.2.7 on 2026-07-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_chatmessage_image_remove_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='logo2.png', max_length=150),
        ),
    ]
