# Generated by Django 5.2.7 on 2026-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Animation', 'Animation'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama')], max_length=50)),
                ('poster', models.ImageField(upload_to='movies/')),
                ('year', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('watch_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
