# Generated by Django 5.2.7 on 2026-07-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='embed_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
