# Generated by Django 5.2.7 on 2026-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_movie_embed_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='games/')),
                ('game_type', models.CharField(choices=[('ONLINE', 'Online Game'), ('OFFLINE', 'Offline Game')], max_length=20)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('ANDROID', 'Android'), ('WEB', 'Web')], max_length=20)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('play_link', models.URLField(blank=True)),
                ('embed_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='offline_games/')),
                ('download_link', models.URLField()),
                ('size', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='online_games/')),
                ('game_link', models.URLField()),
                ('embed_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='Action', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
