# Generated by Django 5.2.7 on 2026-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_game_offlinegame_onlinegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='download_link',
            field=models.URLField(blank=True),
        ),
    ]
