# Generated by Django 5.2.7 on 2026-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_game_download_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-globe', 'Web'), ('fa-code', 'Development'), ('fa-gamepad', 'Games'), ('fa-desktop', 'Operating System'), ('fa-shield-halved', 'Security'), ('fa-ruler-combined', 'Design'), ('fa-microchip', 'Simulation'), ('fa-mobile-screen', 'Mobile Apps'), ('fa-film', 'Movies'), ('fa-music', 'Music'), ('fa-camera', 'Photography'), ('fa-robot', 'AI'), ('fa-book', 'Books'), ('fa-network-wired', 'Networking'), ('fa-cloud', 'Cloud'), ('fa-database', 'Database'), ('fa-terminal', 'Terminal'), ('fa-laptop-code', 'Programming'), ('fa-folder-open', 'Other')], default='fa-folder-open', max_length=50),
        ),
    ]
