# Generated by Django 5.2.7 on 2026-07-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_category_image_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-globe', 'Web'), ('fa-code', 'Development'), ('fa-laptop-code', 'Programming'), ('fa-terminal', 'Terminal'), ('fa-server', 'Server'), ('fa-database', 'Database'), ('fa-file-code', 'Source Code'), ('fa-code-branch', 'Version Control'), ('fa-sitemap', 'Architecture'), ('fa-cubes', 'Frameworks'), ('fa-gamepad', 'Games'), ('fa-dice', 'Gaming Tools'), ('fa-trophy', 'Achievements'), ('fa-film', 'Movies'), ('fa-music', 'Music'), ('fa-headphones', 'Audio'), ('fa-photo-film', 'Media'), ('fa-camera', 'Photography'), ('fa-video', 'Video Editing'), ('fa-desktop', 'Operating System'), ('fa-laptop', 'Laptop Software'), ('fa-computer', 'Computer'), ('fa-mobile-screen', 'Mobile Apps'), ('fa-tablet-screen-button', 'Tablet'), ('fa-tv', 'Smart TV'), ('fa-shield-halved', 'Security'), ('fa-lock', 'Privacy'), ('fa-key', 'Encryption'), ('fa-user-secret', 'Hacking Tools'), ('fa-virus', 'Antivirus'), ('fa-bug', 'Debugging'), ('fa-fingerprint', 'Authentication'), ('fa-eye', 'Monitoring'), ('fa-ruler-combined', 'Design'), ('fa-pen-ruler', 'CAD Design'), ('fa-palette', 'Graphics'), ('fa-image', 'Images'), ('fa-object-group', 'UI Design'), ('fa-cube', '3D Modeling'), ('fa-compass-drafting', 'Engineering'), ('fa-microchip', 'Simulation'), ('fa-memory', 'Hardware'), ('fa-bolt', 'Electronics'), ('fa-gears', 'Engineering Tools'), ('fa-robot', 'Robotics'), ('fa-wave-square', 'Signal Processing'), ('fa-robot', 'Artificial Intelligence'), ('fa-brain', 'Machine Learning'), ('fa-chart-line', 'Data Analysis'), ('fa-chart-column', 'Statistics'), ('fa-database', 'Data Science'), ('fa-network-wired', 'Networking'), ('fa-wifi', 'Wireless'), ('fa-cloud', 'Cloud'), ('fa-cloud-arrow-down', 'Cloud Download'), ('fa-globe-americas', 'Internet'), ('fa-link', 'Connections'), ('fa-folder-open', 'Other'), ('fa-folder', 'Files'), ('fa-download', 'Downloads'), ('fa-upload', 'Uploads'), ('fa-box', 'Packages'), ('fa-wrench', 'Utilities'), ('fa-screwdriver-wrench', 'Maintenance'), ('fa-gear', 'Settings'), ('fa-sliders', 'Configuration'), ('fa-comments', 'Chat'), ('fa-comment-dots', 'Messages'), ('fa-broadcast-tower', 'Live Broadcast'), ('fa-video', 'Live Video'), ('fa-microphone', 'Voice'), ('fa-podcast', 'Podcast'), ('fa-signal', 'Live Signal'), ('fa-circle', 'Online Status'), ('fa-book', 'Books'), ('fa-file', 'Documents'), ('fa-file-pdf', 'PDF'), ('fa-file-word', 'Documents Editor'), ('fa-file-excel', 'Spreadsheets')], default='fa-folder-open', max_length=50),
        ),
    ]
