# Generated by Django 5.2.7 on 2026-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-globe', 'Web'), ('fa-code', 'Development'), ('fa-laptop-code', 'Programming'), ('fa-terminal', 'Terminal'), ('fa-server', 'Server'), ('fa-database', 'Database'), ('fa-file-code', 'Source Code'), ('fa-code-branch', 'Version Control'), ('fa-sitemap', 'Architecture'), ('fa-cubes', 'Frameworks'), ('fa-gamepad', 'Games'), ('fa-dice', 'Gaming Tools'), ('fa-trophy', 'Achievements'), ('fa-film', 'Movies'), ('fa-music', 'Music'), ('fa-headphones', 'Audio'), ('fa-photo-film', 'Media'), ('fa-camera', 'Photography'), ('fa-video', 'Video Editing'), ('fa-desktop', 'Operating System'), ('fa-laptop', 'Laptop Software'), ('fa-computer', 'Computer'), ('fa-mobile-screen', 'Mobile Apps'), ('fa-tablet-screen-button', 'Tablet'), ('fa-tv', 'Smart TV'), ('fa-shield-halved', 'Security'), ('fa-lock', 'Privacy'), ('fa-key', 'Encryption'), ('fa-user-secret', 'Hacking Tools'), ('fa-virus', 'Antivirus'), ('fa-bug', 'Debugging'), ('fa-fingerprint', 'Authentication'), ('fa-eye', 'Monitoring'), ('fa-ruler-combined', 'Design'), ('fa-pen-ruler', 'CAD Design'), ('fa-palette', 'Graphics'), ('fa-image', 'Images'), ('fa-object-group', 'UI Design'), ('fa-cube', '3D Modeling'), ('fa-compass-drafting', 'Engineering'), ('fa-microchip', 'Simulation'), ('fa-memory', 'Hardware'), ('fa-bolt', 'Electronics'), ('fa-gears', 'Engineering Tools'), ('fa-robot', 'Robotics'), ('fa-wave-square', 'Signal Processing'), ('fa-robot', 'Artificial Intelligence'), ('fa-brain', 'Machine Learning'), ('fa-chart-line', 'Data Analysis'), ('fa-chart-column', 'Statistics'), ('fa-database', 'Data Science'), ('fa-network-wired', 'Networking'), ('fa-wifi', 'Wireless'), ('fa-cloud', 'Cloud'), ('fa-cloud-arrow-down', 'Cloud Download'), ('fa-globe-americas', 'Internet'), ('fa-link', 'Connections'), ('fa-folder-open', 'Other'), ('fa-folder', 'Files'), ('fa-download', 'Downloads'), ('fa-upload', 'Uploads'), ('fa-box', 'Packages'), ('fa-wrench', 'Utilities'), ('fa-screwdriver-wrench', 'Maintenance'), ('fa-gear', 'Settings'), ('fa-sliders', 'Configuration'), ('fa-comments', 'Chat'), ('fa-comment-dots', 'Messages'), ('fa-broadcast-tower', 'Live Broadcast'), ('fa-video', 'Live Video'), ('fa-microphone', 'Voice'), ('fa-podcast', 'Podcast'), ('fa-signal', 'Live Signal'), ('fa-circle', 'Online Status'), ('fa-book', 'Books'), ('fa-file', 'Documents'), ('fa-file-pdf', 'PDF'), ('fa-file-word', 'Documents Editor'), ('fa-file-excel', 'Spreadsheets'), ('fa-futbol', 'Football'), ('fa-football', 'American Football'), ('fa-trophy', 'Sports'), ('fa-medal', 'Championship'), ('fa-ranking-star', 'Rankings'), ('fa-person-running', 'Player'), ('fa-users', 'Teams'), ('fa-user-tie', 'Coach'), ('fa-whistle', 'Referee'), ('fa-calendar-days', 'Fixtures'), ('fa-clock', 'Match Time'), ('fa-chart-line', 'Statistics'), ('fa-chart-simple', 'Performance'), ('fa-tv', 'Live Matches'), ('fa-video', 'Football Videos'), ('fa-camera', 'Match Photos'), ('fa-microphone', 'Sports Commentary'), ('fa-radio', 'Live Radio'), ('fa-bullseye', 'Goals'), ('fa-fire', 'Hot Matches'), ('fa-star', 'Favorite Team'), ('fa-shield', 'Club Defense'), ('fa-location-dot', 'Stadium'), ('fa-flag', 'Country Teams'), ('fa-earth-africa', 'World Football'), ('fa-ticket', 'Match Tickets'), ('fa-newspaper', 'Sports News'), ('fa-gamepad', 'Football Games'), ('fa-mobile-screen', 'Football Apps'), ('fa-database', 'Player Database'), ('fa-globe', 'Football Website')], default='fa-folder-open', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('series', 'series'), ('Film', 'Film'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Animation', 'Animation'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama')], max_length=50),
        ),
    ]
