# Generated by Django 5.2.7 on 2026-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_category_icon_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Series', 'Series'), ('Film', 'Film'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Animation', 'Animation'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama')], max_length=50),
        ),
    ]
