# Generated by Django 5.2.7 on 2026-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestream',
            old_name='youtube_live',
            new_name='watch_link',
        ),
        migrations.AddField(
            model_name='livestream',
            name='embed_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
