# Generated by Django 5.2.7 on 2026-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
