# Generated by Django 5.2.7 on 2026-07-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_chatmessage_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
