# Generated by Django 5.2.7 on 2026-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_profile_avatar_choice_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_selected',
            field=models.BooleanField(default=False),
        ),
    ]
